name: eda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - statsmodels
  - jupyterlab
  - ipywidgets
  - openpyxl
  - xlrd
  - pip
  - pip:
      - pandas-profiling
      - sweetviz
